// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0F-_VyeeS8tPlXUkD4s993wNFGJWGMHM',
    appId: '1:958802338788:web:721ae8d2996eeb8d745df1',
    messagingSenderId: '958802338788',
    projectId: 'ridemate-c626f',
    authDomain: 'ridemate-c626f.firebaseapp.com',
    storageBucket: 'ridemate-c626f.firebasestorage.app',
    measurementId: 'G-167ZFL1ZN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIeqz7va884ao1H7EjWI1GjM24_glRFzA',
    appId: '1:958802338788:android:d9874d8da808e2bc745df1',
    messagingSenderId: '958802338788',
    projectId: 'ridemate-c626f',
    storageBucket: 'ridemate-c626f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1C4wkuZbu8NLz7WoyIXL-TGxkmZLwsOs',
    appId: '1:958802338788:ios:618bf4d35e289a3b745df1',
    messagingSenderId: '958802338788',
    projectId: 'ridemate-c626f',
    storageBucket: 'ridemate-c626f.firebasestorage.app',
    iosClientId: '958802338788-gg1n8lsvula229tkcseafvslrf9m5j8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridemate4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1C4wkuZbu8NLz7WoyIXL-TGxkmZLwsOs',
    appId: '1:958802338788:ios:618bf4d35e289a3b745df1',
    messagingSenderId: '958802338788',
    projectId: 'ridemate-c626f',
    storageBucket: 'ridemate-c626f.firebasestorage.app',
    iosClientId: '958802338788-gg1n8lsvula229tkcseafvslrf9m5j8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridemate4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0F-_VyeeS8tPlXUkD4s993wNFGJWGMHM',
    appId: '1:958802338788:web:0ab863db0a0c2d68745df1',
    messagingSenderId: '958802338788',
    projectId: 'ridemate-c626f',
    authDomain: 'ridemate-c626f.firebaseapp.com',
    storageBucket: 'ridemate-c626f.firebasestorage.app',
    measurementId: 'G-BNMSKXJK27',
  );
}
